language: node_js
sudo: false
services:
  - mysql
  - postgresql
node_js:
  - 8.4.0
  - 8.9.0
  - 9.0.0
  - 10.16.3
  - 12.18.4
  - 12.20.0
before_script:
  - npm install -g mocha
  - mysql -e "create database IF NOT EXISTS test;" -uroot
  - psql -c 'create database test;' -U postgres
script: npm test
