language: node_js
sudo: false
node_js:
  - "0.12"
addons:
  postgresql: "9.3"
before_script:
  - npm install -g mocha
  - mysql -e "create database IF NOT EXISTS test;" -uroot
  - psql -c 'create database test;' -U postgres
script: npm test