// Generated by CoffeeScript 1.6.3
(function() {
  var Car, ManagedObject,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  ManagedObject = require('./../../lib/ManagedObject');

  Car = (function(_super) {
    __extends(Car, _super);

    function Car() {
      Car.__super__.constructor.apply(this, arguments);
    }

    Car.prototype.setBrandCustom = function(value) {
      return this.brand = value + value;
    };

    Car.prototype.getOwnerCustom = function(callback) {
      return this.getOwner(callback);
    };

    return Car;

  })(ManagedObject);

  module.exports = Car;

}).call(this);
