// Generated by CoffeeScript 1.10.0
(function() {
  var Hello, ManagedObject,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  ManagedObject = require('./../../lib/ManagedObject');

  Hello = (function(superClass) {
    extend(Hello, superClass);

    function Hello() {
      return Hello.__super__.constructor.apply(this, arguments);
    }

    Hello.prototype.awakeFromInsert = function() {
      Hello.__super__.awakeFromInsert.apply(this, arguments);
      return this.awakeFromInsertValue = 'awaken';
    };

    Hello.prototype.awakeFromFetch = function() {
      Hello.__super__.awakeFromFetch.apply(this, arguments);
      return this.awakeFromFetchValue = 'fetched';
    };

    Hello.prototype.willSave = function() {
      return this.saveValue = 'will save';
    };

    Hello.prototype.didSave = function() {
      return this.saveValue = 'did save';
    };

    Hello.prototype.getFullName = function() {
      return this.firstname + ' ' + this.lastname;
    };

    Hello.prototype.setFullName = function(fullName) {
      var parts;
      if (fullName === null) {
        this.firstname = null;
        return this.lastname = null;
      } else {
        parts = fullName.split(' ');
        this.firstname = parts[0];
        return this.lastname = parts[1];
      }
    };

    Hello.prototype.getFullName2 = function() {
      return this.firstname + ' ' + this.lastname;
    };

    return Hello;

  })(ManagedObject);

  module.exports = Hello;

}).call(this);
