// Generated by CoffeeScript 1.9.3
(function() {
  var ManagedObject, Owner,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  ManagedObject = require('./../../lib/ManagedObject');

  Owner = (function(superClass) {
    extend(Owner, superClass);

    function Owner() {
      return Owner.__super__.constructor.apply(this, arguments);
    }

    return Owner;

  })(ManagedObject);

  module.exports = Owner;

}).call(this);
