// Generated by CoffeeScript 1.6.3
(function() {
  var ManagedObject, Owner, _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  ManagedObject = require('./../../lib/ManagedObject');

  Owner = (function(_super) {
    __extends(Owner, _super);

    function Owner() {
      _ref = Owner.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    return Owner;

  })(ManagedObject);

  module.exports = Owner;

}).call(this);
