// Generated by CoffeeScript 1.10.0
(function() {
  var ManagedObject, User,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  ManagedObject = require('./../../lib/ManagedObject');

  User = (function(superClass) {
    extend(User, superClass);

    function User() {
      return User.__super__.constructor.apply(this, arguments);
    }

    User.prototype.getFirstname = function() {
      return this._getFirstname();
    };

    User.prototype.getFullName = function() {
      return this.firstname + ' ' + this.lastname;
    };

    User.prototype.setFullName = function(fullName) {
      var parts;
      parts = fullName.split(' ');
      this.firstname = parts[0];
      return this.lastname = parts[1];
    };

    return User;

  })(ManagedObject);

  module.exports = User;

}).call(this);
