// Generated by CoffeeScript 1.6.3
(function() {
  var AtomicStore, PersistentStore, _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  PersistentStore = require('./PersistentStore');

  AtomicStore = (function(_super) {
    __extends(AtomicStore, _super);

    function AtomicStore() {
      _ref = AtomicStore.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    return AtomicStore;

  })(PersistentStore);

  module.exports = AtomicStore;

}).call(this);
