// Generated by CoffeeScript 1.10.0
(function() {
  var AtomicStore, PersistentStore,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  PersistentStore = require('./PersistentStore');

  AtomicStore = (function(superClass) {
    extend(AtomicStore, superClass);

    function AtomicStore() {
      return AtomicStore.__super__.constructor.apply(this, arguments);
    }

    return AtomicStore;

  })(PersistentStore);

  module.exports = AtomicStore;

}).call(this);
