// Generated by CoffeeScript 1.6.3
(function() {
  var IncrementalStoreNode;

  IncrementalStoreNode = (function() {
    function IncrementalStoreNode() {}

    IncrementalStoreNode.prototype.contructor = function(objectId, values, version) {
      this.objectId = objectId;
      this.values = values;
      this.version = version;
    };

    return IncrementalStoreNode;

  })();

  module.exports = IncrementalStoreNode;

}).call(this);
