// Generated by CoffeeScript 1.9.3
(function() {
  var PersistentStore;

  PersistentStore = (function() {
    function PersistentStore(persistentStoreCoordinator, URL) {
      this.persistentStoreCoordinator = persistentStoreCoordinator;
      this.URL = URL;
    }

    PersistentStore.prototype.getType = function() {
      throw new Error('method must be overwritten');
    };

    PersistentStore.prototype.syncSchema = function(options, callback) {
      throw new Error('method must be overwritten');
    };

    return PersistentStore;

  })();

  module.exports = PersistentStore;

}).call(this);
