// Generated by CoffeeScript 1.9.3
(function() {
  var PersistentStoreRequest;

  PersistentStoreRequest = (function() {
    function PersistentStoreRequest(type) {
      this.type = type;
    }

    PersistentStoreRequest.prototype.insertedObjects = function() {
      return [];
    };

    PersistentStoreRequest.prototype.updatedObjects = function() {
      return [];
    };

    PersistentStoreRequest.prototype.deletedObjects = function() {
      return [];
    };

    PersistentStoreRequest.prototype.lockedObjects = function() {
      return [];
    };

    return PersistentStoreRequest;

  })();

  module.exports = PersistentStoreRequest;

}).call(this);
