// Generated by CoffeeScript 1.6.3
(function() {
  var SortDescriptor,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  SortDescriptor = (function(_super) {
    __extends(SortDescriptor, _super);

    function SortDescriptor(attribute, ascending) {
      this.attribute = attribute;
      if (ascending == null) {
        ascending = true;
      }
      this.ascending = !!ascending;
    }

    SortDescriptor.prototype.toString = function() {
      return this.attribute + ' ' + (this.ascending ? 'ASC' : 'DESC');
    };

    return SortDescriptor;

  })(Object);

  module.exports = SortDescriptor;

}).call(this);
