// Generated by CoffeeScript 1.6.3
(function() {
  var AttributeDescription, PropertyDescription,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  PropertyDescription = require('./PropertyDescription');

  AttributeDescription = (function(_super) {
    __extends(AttributeDescription, _super);

    function AttributeDescription(type, info, name, entity) {
      this.type = type;
      this.info = info;
      AttributeDescription.__super__.constructor.call(this, name, entity);
    }

    AttributeDescription.prototype.toString = function() {
      return this.name + '(' + this.type + ')';
    };

    return AttributeDescription;

  })(PropertyDescription);

  module.exports = AttributeDescription;

}).call(this);
