// Generated by CoffeeScript 1.9.3
(function() {
  var AttributeType, emptyFn, validateFn;

  emptyFn = function(value) {
    return value;
  };

  validateFn = function() {
    return true;
  };

  AttributeType = (function() {
    function AttributeType(name, persistentStoreType) {
      this.name = name;
      this.persistentStoreType = persistentStoreType;
      this.transform = emptyFn;
      this.encode = emptyFn;
      this.decode = emptyFn;
      this.validate = validateFn;
    }

    AttributeType.prototype.transformFn = function(fn) {
      this.transform = fn;
      return this;
    };

    AttributeType.prototype.validateFn = function(fn) {
      this.validate = fn;
      return this;
    };

    AttributeType.prototype.encodeFn = function(fn) {
      this.encode = fn;
      return this;
    };

    AttributeType.prototype.decodeFn = function(fn) {
      this.decode = fn;
      return this;
    };

    return AttributeType;

  })();

  module.exports = AttributeType;

}).call(this);
