// Generated by CoffeeScript 1.6.3
(function() {
  var AttributeDescription, EntityDescription, ManagedObject, RelationshipDescription, path;

  AttributeDescription = require('./AttributeDescription');

  RelationshipDescription = require('./RelationshipDescription');

  ManagedObject = require('./../ManagedObject');

  path = require('path');

  EntityDescription = (function() {
    function EntityDescription(name) {
      this.name = name;
      this.attributes = [];
      this.relationships = [];
      this._attributesByName = {};
      this._relationshipsByName = {};
    }

    EntityDescription.prototype.addAttribute = function(attribute) {
      if (attribute instanceof AttributeDescription) {
        attribute.entity = this;
        this.attributes.push(attribute);
        this._attributesByName[attribute.name] = attribute;
      } else {
        throw new Error('attribute ' + attribute + ' is not AttributeDescription');
      }
      return this;
    };

    EntityDescription.prototype.addRelationship = function(relationship) {
      if (relationship instanceof RelationshipDescription) {
        relationship.entity = this;
        this.relationships.push(relationship);
        this._relationshipsByName[relationship.name] = relationship;
      } else {
        throw new Error('relationship ' + relationship + ' is not AttributeDescription');
      }
      return this;
    };

    EntityDescription.prototype.attributesByName = function() {
      return this._attributesByName;
    };

    EntityDescription.prototype.relationshipsByName = function() {
      return this._relationshipsByName;
    };

    return EntityDescription;

  })();

  module.exports = EntityDescription;

}).call(this);
