// Generated by CoffeeScript 1.10.0
(function() {
  var MigrationDescription;

  MigrationDescription = (function() {
    function MigrationDescription() {}

    MigrationDescription.prototype.construct = function(modelFrom, modelTo) {
      this.modelFrom = modelFrom;
      this.modelTo = modelTo;
    };

    MigrationDescription.prototype.appendMigration = function(migration) {};

    MigrationDescription.prototype.addEntity = function(name) {};

    MigrationDescription.prototype.renameEntity = function(oldName, newName) {};

    MigrationDescription.prototype.removeEntity = function(name) {};

    MigrationDescription.prototype.addColumn = function(entityName, name) {};

    MigrationDescription.prototype.renameColumn = function(entityName, oldName, newName) {};

    MigrationDescription.prototype.removeColumn = function(entityName, name) {};

    MigrationDescription.prototype.addRelationship = function(entityName, name) {};

    MigrationDescription.prototype.renameRelationship = function(entityName, oldName, newName) {};

    MigrationDescription.prototype.removeRelationship = function(entityName, name) {};

    MigrationDescription.prototype.addIndex = function(entityName, name) {};

    MigrationDescription.prototype.renameIndex = function(entityName, oldName, newName) {};

    MigrationDescription.prototype.removeIndex = function(entityName, name) {};

    return MigrationDescription;

  })();

  module.exports = MigrationDescription;

}).call(this);
