// Generated by CoffeeScript 1.9.3
(function() {
  var PropertyDescription;

  PropertyDescription = (function() {
    function PropertyDescription(name, entity) {
      this.name = name;
      this.entity = entity;
      this.options = {};
    }

    return PropertyDescription;

  })();

  module.exports = PropertyDescription;

}).call(this);
