// Generated by CoffeeScript 1.6.3
(function() {
  var ManagedObjectID,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  ManagedObjectID = (function(_super) {
    __extends(ManagedObjectID, _super);

    function ManagedObjectID(stringValue, entity) {
      this.stringValue = stringValue;
      this.entity = entity;
      this.stringValue = this.stringValue + '';
      this.isTemporaryID = false;
    }

    ManagedObjectID.prototype.isEqual = function(objectID) {
      return this.toString() === objectID.toString();
    };

    ManagedObjectID.prototype.toString = function() {
      return this.stringValue;
    };

    ManagedObjectID.prototype.recordId = function() {
      var components;
      components = this.stringValue.split('/');
      return components[components.length - 1].replace(/^[pt]/, '');
    };

    return ManagedObjectID;

  })(Object);

  module.exports = ManagedObjectID;

}).call(this);
